### ISSUE TITLE
Error in new preprint branch 

### ISSUE THREAD

**Issue by dannytoomey** [wwiecek/covid-vaccine-timeline#17]
@davidoj I cloned the latest version of the preprint branch and I ran into an error when trying to run on my device. I ran the `run-fits.R` file and got the following error:
```
Error in `map()`:
ℹ In index: 4.
Caused by error in `.f()`:
! ERROR: ABNORMAL_TERMINATION_IN_LNSRCH
Backtrace:
     ▆
  1. ├─orderly::orderly_run("parameters_vaccines", echo = FALSE)
  2. │ └─version$run(...)
  3. │   ├─base::withCallingHandlers(...)
  4. │   └─self$run_execute(echo)
  5. │     ├─withr::with_envvar(...)
  6. │     │ └─base::force(code)
  7. │     ├─withr::with_dir(...)
  8. │     │ └─base::force(code)
  9. │     └─base::source(...)
 10. │       ├─base::withVisible(eval(ei, envir))
 11. │       └─base::eval(ei, envir)
 12. │         └─base::eval(ei, envir)
 13. │           └─... %>% map(fit_curve)
 14. ├─**purrr::map**(., fit_curve)
 15. │ └─purrr:::map_("list", .x, .f, ..., .progress = .progress)
 16. │   ├─purrr:::with_indexed_errors(...)
 17. │   │ └─base::withCallingHandlers(...)
 18. │   ├─purrr:::call_with_cleanup(...)
 19. │   └─.f(.x[[i]], ...)
 20. │     └─base::stop(res$message)
 21. └─base::.handleSimpleError(...)
 22.   └─purrr (local) h(simpleError(msg, call))
 23.     └─cli::cli_abort(...)
 24.       └─rlang::abort(...)
```

I'm trying to figure out what the problem is, but I'm having trouble linking the backtrace to a point source. Do you know what might be going on?

**Comment by davidoj** [comment]
The code is line 343 in `src/parameters_vaccines/script.R`:
```
res <- optim(unlist(par), fn = err_func, method = "L-BFGS-B", lower = lower, upper = upper)
```

The error is a failure of this procedure to converge. It is quite sensitive to the choices of `par`, `lower` and `upper`. You can see between lines 243 and 340 a lot of special cases to set these values to get the procedure to converge. It works on my machine at the moment, but obviously not on yours!

The point of this procedure is to determine the duration of vaccine-derived protection by fitting parameters to an antibody decay curve. I am not sure the benefit of this is actually worth the effort, and if it is too difficult to make this reliable we could simply hardcode the distribution over durations.

To solve the problem: just before the error is raised, R should print the dose/variant combination it was trying to fit. If you could let me know what this is, it may be as simple as dropping this combination from the routine because we're not using it in any simulations down the line - but if it is a dose/variant combination we will use, then it will be necessary to do something different.

**Comment by dannytoomey** [comment]
Got it, thanks David! The dose/variant combination it is trying to fit when it fails is `Second; Delta; Adenovirus`. I will adjust the `par`, `lower`, and `upper parameter` and see if I can get converge on my machine.

**Comment by davidoj** [comment]
We don't use that vaccine type. I pushed a new update that removes it from the fitting routine.
